#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if /home/tails/build-server/cheese-engine/tools/build-system/scripts/build-target "$(pwd)" "Debug-Linux-x86_64" ; then
    /home/tails/build-server/cheese-engine/tools/build-information "$(pwd)"
    echo "Build completed successfully"
    exit 0
else
    echo "Build failed"
    exit 1
fi
